#/usr/bin/perl -w
#
# whip6: Warsaw High-performance IPv6.
#
# Copyright (c) 2012-2017 Konrad Iwanicki
# All rights reserved.
#
# This file is distributed under the terms in the attached LICENSE     
# files.
#

my @inputFiles = @ARGV;
my @includeFiles = ();
foreach my $incFile (@inputFiles) {
    push(@includeFiles, extractInternalIncludePath($incFile));
}

print "/**\n";
print " * whip6: Warsaw High-performance IPv6.\n";
print " *\n";
print " * Copyright (c) 2012, <\@OUR_COMPANY_NAME\@>\n";
print " * All rights reserved.\n";
print " */\n";
print "#ifndef __WHIP6_MICROC_LIB_FOR_NESC_H__\n";
print "#define __WHIP6_MICROC_LIB_FOR_NESC_H__\n\n";
print "/**\n";
print " * \@file\n";
print " *\n";
print " * This file is automatically generated by the whip6 toolchain.\n";
print " * It contains all the necessary headers for nesc.\n";
print " */\n\n";
#print "#define WHIP6_MICROC_EXTERN_DECL_PREFIX extern\n";
#print "#define WHIP6_MICROC_EXTERN_DECL_SUFFIX __attribute__((banked))\n";
#print "#define WHIP6_MICROC_EXTERN_DEF_PREFIX\n";
#print "#define WHIP6_MICROC_EXTERN_DEF_SUFFIX __attribute__((banked))\n";
#print "#define WHIP6_MICROC_PRIVATE_DECL_PREFIX static\n";
#print "#define WHIP6_MICROC_PRIVATE_DECL_SUFFIX\n";
#print "#define WHIP6_MICROC_PRIVATE_DEF_PREFIX static\n";
#print "#define WHIP6_MICROC_PRIVATE_DEF_SUFFIX\n";
#print "#define WHIP6_MICROC_INLINE_DECL_PREFIX inline\n";
#print "#define WHIP6_MICROC_INLINE_DECL_SUFFIX\n";
#print "#define WHIP6_MICROC_INLINE_DEF_PREFIX inline\n";
#print "#define WHIP6_MICROC_INLINE_DEF_SUFFIX\n\n";
foreach my $incFile (@includeFiles) {
    print "#include <$incFile>\n";
}
print "\n";
print "#endif /* __WHIP6_MICROC_LIB_FOR_NESC_H__ */\n";


sub extractInternalIncludePath
{
    local $orgPath = $_[0];
    #local $idxFirst = rindex($orgPath, "include/");
    local $idxFirst = rindex($orgPath, "cc253x-standard/");
    if ($idxFirst < 0)
    {
        $orgPath;
    }
    else
    {
        #local $idxLast = $idxFirst + length("include/");
        local $idxLast = $idxFirst + length("cc253x-standard/");
        substr($orgPath, $idxLast);
    }
}

sub isIncludeFileInternal
{
    local $incPath = $_[0];
    local $res = 0;
    foreach my $incFile (@includeFiles) {
        if ($incFile eq $incPath)
        {
            $res = 1;
            last;
        }
    }
    $res;
}
