/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     UART Emulator
  * - <b>Project file</b>:     C:/Users/badge/Documents/Texas Instruments/Sensor Controller Studio/examples/uart_emulator/uart_emulator.scp
  * - <b>Code prefix</b>:      -
  * - <b>Operating system</b>: None
  * - <b>Tool version</b>:     1.3.1.42689
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC2650, revision -, package QFN48 7x7 RGZ
  * - <b>Created</b>:          2017-02-12 11:31:56.126
  * - <b>Computer</b>:         DESKTOP-DACKC3I
  * - <b>User</b>:             badge
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (i.e. Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * Demonstrates the UART Emulator functionality on the SmartRF06 Evaluation Board
  * 
  * See the description of the UART Emulator resource for details.
  * The System CPU application implements simple loop-back of received data. The UART RX and TX pins are
  * mapped to the SmartRF06EB's USB Serial Port.
  * 
  * See the header in the application source file ("main.c" or similar) for further details and
  * instructions. This file is located in the source code output directory.
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - UART Emulator:
  *     - <b>UART RX</b>: DIO29
  *     - <b>UART TX</b>: DIO28
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_uart_emulator UART Emulator
  * Emulates a UART interface.
  * 
  * See the description of the UART Emulator resource for details.
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     UART Emulator
  * - <b>Code prefix</b>:      -
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  *
  * @{
  */
#ifndef SCIF_H
#define SCIF_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_whip6.h"


/// Target chip name
#define SCIF_TARGET_CHIP_NAME_CC2650
/// Target chip package
#define SCIF_TARGET_CHIP_PACKAGE_QFN48_7X7_RGZ

/// Number of tasks implemented by this driver
#define SCIF_TASK_COUNT 1

/// UART Emulator: Task ID
#define SCIF_UART_EMULATOR_TASK_ID 0


/// UART Emulator I/O mapping: UART RX
#define SCIF_UART_EMULATOR_DIO_UART_RX 29
/// UART Emulator I/O mapping: UART TX
#define SCIF_UART_EMULATOR_DIO_UART_TX 28


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// UART Emulator: Task input data structure
typedef struct {
    uint16_t pTxBuffer[768]; ///< TX FIFO ring buffer
} SCIF_UART_EMULATOR_INPUT_T;


/// UART Emulator: Task state structure
typedef struct {
    uint16_t txHead; ///< TX FIFO head index (updated by the application)
    uint16_t txTail; ///< TX FIFO tail index (updated by the Sensor Controller)
} SCIF_UART_EMULATOR_STATE_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_UART_EMULATOR_INPUT_T input;
        SCIF_UART_EMULATOR_STATE_T state;
    } uartEmulator;
} SCIF_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifTaskData    (*((volatile SCIF_TASK_DATA_T*) 0x400E00E6))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifDriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifReinitTaskIo(uint32_t bvTaskIds);


/// Maximum number of characters that can be stored in the UART TX FIFO
#define SCIF_UART_TX_FIFO_MAX_COUNT                  767

void scifUartSetBaudRate(uint32_t baudRate);

// UART TX FIFO access functions
uint32_t scifUartGetTxFifoCount(void);
void scifUartTxPutTwoChars(char c1, char c2);
void scifUartTxPutChar(char c);
void scifUartTxPutChars(char* pBuffer, uint32_t count);


#endif
//@}


// Generated by DESKTOP-DACKC3I at 2017-02-12 11:31:56.126
