/*
 * whip6: Warsaw High-performance IPv6.
 *
 * Copyright (c) 2012-2016 InviNets Sp z o.o.
 * All rights reserved.
 *
 * This file is distributed under the terms in the attached LICENSE     
 * files. If you do not find these files, copies can be found by writing
 * to technology@invinets.com.
 */

/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     Power Consumption Test
  * - <b>Project file</b>:     Z:/projekty/prztyczek/whip6/nesc/whip6/platforms/boards/cc26xxbased/sensortag2/scif_pwrtest/pwrtest.scp
  * - <b>Code prefix</b>:      PWRTEST
  * - <b>Operating system</b>: None
  * - <b>Tool version</b>:     1.2.1.40829
  * - <b>Target chip</b>:      CC2650, revision -, package QFN48 7x7 RGZ
  * - <b>Created</b>:          2016-04-17 22:55:51.289
  * - <b>Computer</b>:         ACWIN8
  * - <b>User</b>:             accek
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (i.e. Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * No description entered
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - Power Consumption Test:
  *     - <b>O: Test Pin</b>: DIO27
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_power_consumption_test Power Consumption Test
  * No description entered
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     Power Consumption Test
  * - <b>Code prefix</b>:      PWRTEST
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  *
  * @{
  */
#ifndef SCIF_PWRTEST_H
#define SCIF_PWRTEST_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_none.h"


/// Target chip name
#define SCIF_PWRTEST_TARGET_CHIP_NAME_CC2650
/// Target chip package
#define SCIF_PWRTEST_TARGET_CHIP_PACKAGE_QFN48_7X7_RGZ

/// Number of tasks implemented by this driver
#define SCIF_PWRTEST_TASK_COUNT 1

/// Power Consumption Test: Task ID
#define SCIF_PWRTEST_POWER_CONSUMPTION_TEST_TASK_ID 0


/// Power Consumption Test I/O mapping: Test Pin
#define SCIF_PWRTEST_POWER_CONSUMPTION_TEST_DIO_O_TEST_PIN 27


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


// No task data structures defined


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    uint16_t noTaskData;
} SCIF_PWRTEST_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifPwrtestTaskData    (*((volatile SCIF_PWRTEST_TASK_DATA_T*) 0x400E00E6))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifPwrtestDriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifPwrtestReinitTaskIo(uint32_t bvTaskIds);


// RTC-based tick generation control
void scifPwrtestStartRtcTicks(uint32_t tickStart, uint32_t tickPeriod);
void scifPwrtestStartRtcTicksNow(uint32_t tickPeriod);
void scifPwrtestStopRtcTicks(void);


#endif
//@}
